name: encode-string
version: 0.1.0.0
synopsis: Safe string conversion and encoding
description: |
  In modern Haskell many different string types
  are commonly used in combination with the 'OverloadedStrings' extension.
  This small package provides means to convert safely between those.
  Currently, 'String', lazy and strict 'Text', lazy and strict 'ByteString',
  '[Word8]' and 'ShortByteString' are supported.
category: Data, String, Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2017 Daniel Mendler
license: MIT
github: minad/encode-string

extra-source-files:
- "*.md"

ghc-options:
- -Wall

dependencies:
- base                 >= 4.8     && < 5.0
- bytestring           >= 0.9     && < 0.11
- text                 >= 0.7     && < 1.3

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

library:
  source-dirs: src

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - encode-string
      - QuickCheck
      - quickcheck-instances
